import {
  Anchor, Angry, Annoyed, Apple, ArrowBigDown, ArrowBigUp, Atom, Award, Axe, Baby, Banana, Bean, Beer, Bell, Bike, Bird,
  Bomb, Bone, Book, Bookmark, Bot, Brain, Briefcase, Brush, Bug, Bus, CakeSlice, Camera, ChartColumnBig, Car, Carrot, Castle, Cat, Cherry,
  CircleHelp, Citrus, Clapperboard, Cloud, CloudLightning, Clover, Club, Coffee, Cookie, Croissant, Crosshair, Crown,
  Dessert, Diamond, Dices, Dog, Donut, Drama, Droplet, Drumstick, Egg, Feather, Fingerprint, Fish, FishSymbol, Flag,
  FlaskConical, Flame, Flower, Footprints, Frown, Gamepad2, Gem, Ghost, Gift, Grape, Guitar, Ham, HandMetal, Handshake,
  Headphones, Heart, HeartPulse, Hexagon, Hourglass, IceCreamCone, Laugh, Layers, Leaf, LeafyGreen, Lightbulb, Lollipop,
  Magnet, Medal, Meh, Moon, Mountain, Music, Origami, Palette, PartyPopper, PawPrint, Piano, Pickaxe, Pizza, Plane, Pointer,
  Popcorn, Puzzle, Rabbit, Radar, Radiation, Rainbow, Rat, Ribbon, Rocket, Sailboat, Salad, Sandwich, Shell, Shield,
  Ship, Shirt, Siren, Skull, Smile, SmilePlus, Snail, Spade, Sparkles, SquareStack, Squirrel, Star, ThumbsDown, ThumbsUp,
  Tractor, TreeDeciduous, TreePalm, TreePine, Trophy, Truck, Umbrella, VenetianMask, Worm, Zap,
} from "lucide-react";

// Stored in the player's `emoji` field.
export const PLAYER_ICON_LIBRARY = [
  // Characters
  ["smile", Smile, "smile happy face joy grin"],
  ["laugh", Laugh, "laugh haha joy funny grin"],
  ["smile-plus", SmilePlus, "smile happy face add wink"],
  ["meh", Meh, "meh whatever neutral face"],
  ["annoyed", Annoyed, "annoyed eye roll whatever face"],
  ["frown", Frown, "frown sad unhappy face"],
  ["angry", Angry, "angry mad rage furious face"],
  ["ghost", Ghost, "ghost spooky boo halloween"],
  ["skull", Skull, "skull death dead bones pirate"],
  ["bot", Bot, "robot bot ai tech mech"],
  ["crown", Crown, "crown king queen royal winner boss"],
  ["baby", Baby, "baby kid child young"],
  ["venetian-mask", VenetianMask, "mask masquerade mystery disguise"],
  ["drama", Drama, "drama theater masks comedy tragedy"],
  ["hand-metal", HandMetal, "rock metal horns hand music"],
  ["thumbs-up", ThumbsUp, "thumbs up like good yes ok"],
  ["thumbs-down", ThumbsDown, "thumbs down dislike bad no"],
  ["brain", Brain, "brain smart genius think nerd"],
  ["fingerprint", Fingerprint, "fingerprint identity detective spy"],
  ["footprints", Footprints, "footprints feet walk steps"],

  // Animals
  ["cat", Cat, "cat kitten kitty pet animal"],
  ["dog", Dog, "dog puppy pet animal"],
  ["rabbit", Rabbit, "rabbit bunny easter pet animal"],
  ["squirrel", Squirrel, "squirrel chipmunk nuts animal"],
  ["rat", Rat, "rat mouse rodent animal"],
  ["bird", Bird, "bird fly tweet animal"],
  ["origami", Origami, "origami bird crane paper"],
  ["fish", Fish, "fish sea ocean animal"],
  ["fish-symbol", FishSymbol, "fish sea ocean swim"],
  ["snail", Snail, "snail slow shell turtle"],
  ["bug", Bug, "bug insect beetle"],
  ["worm", Worm, "worm wiggle bait"],
  ["shell", Shell, "shell snail spiral sea beach"],
  ["paw-print", PawPrint, "paw print pet animal dog cat"],
  ["egg", Egg, "egg chick breakfast"],
  ["bone", Bone, "bone dog skeleton"],
  ["feather", Feather, "feather bird light quill"],

  // Nature
  ["flame", Flame, "fire flame hot lit"],
  ["zap", Zap, "lightning bolt flash zap fast"],
  ["star", Star, "star shine favorite"],
  ["sparkles", Sparkles, "sparkles magic shine glitter"],
  ["heart", Heart, "heart love"],
  ["moon", Moon, "moon night crescent"],
  ["cloud", Cloud, "cloud sky weather"],
  ["cloud-lightning", CloudLightning, "storm thunder lightning cloud weather"],
  ["rainbow", Rainbow, "rainbow pride colors"],
  ["droplet", Droplet, "drop water tear rain"],
  ["leaf", Leaf, "leaf plant nature green"],
  ["clover", Clover, "clover lucky shamrock four leaf"],
  ["flower", Flower, "flower blossom petal"],
  ["tree-pine", TreePine, "tree pine evergreen forest"],
  ["tree-deciduous", TreeDeciduous, "tree forest leaves oak"],
  ["tree-palm", TreePalm, "palm tree tropical beach"],
  ["mountain", Mountain, "mountain peak hike climb"],
  ["atom", Atom, "atom science nerd physics"],

  // Food
  ["pizza", Pizza, "pizza food slice italian"],
  ["sandwich", Sandwich, "sandwich burger food lunch"],
  ["drumstick", Drumstick, "drumstick chicken leg food"],
  ["ham", Ham, "ham meat food"],
  ["croissant", Croissant, "croissant pastry bread breakfast"],
  ["salad", Salad, "salad food healthy"],
  ["carrot", Carrot, "carrot vegetable food"],
  ["leafy-green", LeafyGreen, "lettuce greens vegetable food"],
  ["bean", Bean, "bean legume food"],
  ["apple", Apple, "apple fruit red"],
  ["cherry", Cherry, "cherry fruit red"],
  ["citrus", Citrus, "orange lemon lime citrus fruit"],
  ["banana", Banana, "banana fruit yellow"],
  ["grape", Grape, "grapes fruit"],
  ["cookie", Cookie, "cookie food sweet"],
  ["donut", Donut, "donut doughnut food sweet"],
  ["cake-slice", CakeSlice, "cake slice birthday food sweet"],
  ["dessert", Dessert, "dessert cupcake pudding sweet"],
  ["ice-cream-cone", IceCreamCone, "ice cream cone sweet"],
  ["lollipop", Lollipop, "lollipop candy sweet treat"],
  ["popcorn", Popcorn, "popcorn movie snack"],
  ["coffee", Coffee, "coffee drink hot caffeine"],
  ["beer", Beer, "beer drink alcohol cheers"],

  // Games
  ["trophy", Trophy, "trophy winner champion award gold"],
  ["medal", Medal, "medal award winner first"],
  ["award", Award, "award ribbon prize winner"],
  ["ribbon", Ribbon, "ribbon award cause"],
  ["target", Crosshair, "target bullseye aim crosshair"],
  ["dices", Dices, "dice game roll luck"],
  ["spade", Spade, "spade card suit"],
  ["club", Club, "club card suit clover"],
  ["diamond", Diamond, "diamond card suit"],
  ["gem", Gem, "gem diamond jewel rich"],
  ["gamepad", Gamepad2, "controller game video gaming"],
  ["puzzle", Puzzle, "puzzle jigsaw piece"],
  ["shield", Shield, "shield defense protect knight"],
  ["axe", Axe, "axe viking lumberjack weapon"],
  ["pickaxe", Pickaxe, "pickaxe mine dig craft"],
  ["bomb", Bomb, "bomb explode boom"],
  ["magnet", Magnet, "magnet attract pull"],
  ["hexagon", Hexagon, "hexagon shape honeycomb"],
  ["party-popper", PartyPopper, "party popper celebrate confetti"],
  ["gift", Gift, "gift present box birthday"],

  // Vehicles & things
  ["rocket", Rocket, "rocket space launch fast"],
  ["plane", Plane, "airplane plane travel fly"],
  ["car", Car, "car drive race"],
  ["bus", Bus, "bus school travel"],
  ["truck", Truck, "truck delivery drive"],
  ["tractor", Tractor, "tractor farm drive"],
  ["bike", Bike, "bicycle bike ride"],
  ["sailboat", Sailboat, "sailboat boat sail sea"],
  ["ship", Ship, "ship boat cruise sea"],
  ["anchor", Anchor, "anchor boat navy sea"],
  ["castle", Castle, "castle king queen fortress"],
  ["guitar", Guitar, "guitar music rock"],
  ["piano", Piano, "piano music keys"],
  ["music", Music, "music note song"],
  ["headphones", Headphones, "headphones music audio dj"],
  ["palette", Palette, "art palette paint creative"],
  ["brush", Brush, "brush paint art"],
  ["camera", Camera, "camera photo picture"],
  ["clapperboard", Clapperboard, "movie film director action"],
  ["book", Book, "book read study learn"],
  ["briefcase", Briefcase, "briefcase work business job"],
  ["lightbulb", Lightbulb, "lightbulb idea smart bright"],
  ["flask", FlaskConical, "flask science potion chemistry"],
  ["radiation", Radiation, "radiation nuclear toxic danger"],
  ["radar", Radar, "radar scan detect"],
  ["siren", Siren, "siren alarm police emergency"],
  ["bell", Bell, "bell ring alert"],
  ["hourglass", Hourglass, "hourglass time wait slow"],
  ["heart-pulse", HeartPulse, "heartbeat pulse health"],
  ["umbrella", Umbrella, "umbrella rain weather"],
  ["shirt", Shirt, "shirt tshirt clothes jersey"],
];

// UI glyphs that aren't offered as player avatars.
const UI_ICONS = {
  "arrow-big-down": ArrowBigDown,
  "arrow-big-up": ArrowBigUp,
  bookmark: Bookmark,
  "chart-column-big": ChartColumnBig,
  "circle-help": CircleHelp,
  flag: Flag,
  handshake: Handshake,
  layers: Layers,
  pointer: Pointer,
  "square-stack": SquareStack,
};

// Random picks for new players should read as a character, not an object.
export const AUTOFILL_ICONS = [
  "smile", "laugh", "ghost", "skull", "bot", "crown", "venetian-mask", "brain",
  "cat", "dog", "rabbit", "squirrel", "rat", "bird", "origami", "fish", "snail", "bug", "worm", "shell",
  "flame", "zap", "star", "sparkles", "moon", "cloud-lightning", "rainbow", "clover", "tree-pine", "mountain",
  "pizza", "croissant", "carrot", "cherry", "banana", "donut", "ice-cream-cone", "popcorn", "coffee",
  "trophy", "dices", "gem", "gamepad", "puzzle", "shield", "axe", "bomb", "party-popper",
  "rocket", "plane", "car", "sailboat", "anchor", "castle", "guitar", "headphones", "palette", "lightbulb", "flask",
];

// Players and game history saved before the switch to Lucide still hold emoji.
const LEGACY_EMOJI = {
  "😀": "smile", "😃": "smile", "😄": "laugh", "😁": "laugh", "😆": "laugh", "😅": "laugh", "🤣": "laugh", "😂": "laugh",
  "🙂": "smile", "🙃": "smile", "😉": "smile-plus", "😊": "smile", "😇": "smile", "🥰": "heart", "😍": "heart",
  "🤩": "star", "😘": "heart", "😋": "smile-plus", "😎": "smile", "🤓": "brain", "🥳": "party-popper", "😏": "smile-plus",
  "😬": "meh", "🤔": "meh", "🤨": "annoyed", "🙄": "annoyed", "😴": "moon", "🤯": "bomb", "🥶": "droplet", "🥵": "flame",
  "😡": "angry", "🤬": "angry", "😈": "angry", "👿": "angry", "💀": "skull", "☠️": "skull", "👻": "ghost", "👽": "bot",
  "👾": "gamepad", "🤖": "bot", "🤡": "drama", "😭": "frown",
  "👑": "crown", "🎩": "venetian-mask", "🧙": "sparkles", "🧛": "skull", "🧟": "skull", "🧞": "sparkles", "🥷": "venetian-mask",
  "🦸": "shield", "🦹": "venetian-mask", "🤠": "star", "💪": "hand-metal", "🙌": "hand-metal", "🤝": "handshake",
  "👍": "thumbs-up", "👎": "thumbs-down", "🫶": "heart",
  "🐶": "dog", "🐩": "dog", "🐺": "dog", "🦊": "dog", "🐱": "cat", "🐯": "cat", "🐅": "cat", "🦁": "cat", "🐆": "cat",
  "🐭": "rat", "🐹": "rat", "🐰": "rabbit", "🐿️": "squirrel", "🦔": "squirrel", "🐻": "paw-print", "🐼": "paw-print",
  "🐻‍❄️": "paw-print", "🐨": "paw-print", "🐵": "paw-print", "🙈": "paw-print", "🦥": "paw-print", "🦦": "paw-print",
  "🐔": "bird", "🐓": "bird", "🐧": "bird", "🐦": "bird", "🦆": "bird", "🦅": "bird", "🦉": "bird", "🦩": "bird",
  "🦚": "bird", "🦜": "bird", "🦢": "origami", "🦃": "bird", "🐠": "fish", "🐟": "fish", "🐬": "fish-symbol",
  "🐳": "fish-symbol", "🦈": "fish-symbol", "🐡": "fish", "🐢": "shell", "🐌": "snail", "🐞": "bug", "🐝": "bug",
  "🦗": "bug", "🕷️": "bug", "🦂": "bug", "🐛": "worm", "🐍": "worm", "🦪": "shell", "🦀": "shell", "🦞": "shell",
  "🦐": "shell", "🐙": "shell", "🦑": "shell", "🦄": "sparkles", "🐉": "flame", "🐲": "flame", "🦖": "bone", "🦕": "bone",
  "🌵": "leaf", "🌲": "tree-pine", "🌴": "tree-palm", "🌳": "tree-deciduous", "🌱": "leaf", "🍀": "clover",
  "🌸": "flower", "🌺": "flower", "🌻": "flower", "🌷": "flower", "🌹": "flower", "💐": "flower",
  "☀️": "sparkles", "🌙": "moon", "⭐": "star", "🌟": "star", "✨": "sparkles", "💫": "sparkles", "⚡": "zap",
  "🔥": "flame", "💥": "bomb", "🌈": "rainbow", "❄️": "droplet", "💧": "droplet", "🌋": "mountain",
  "🍕": "pizza", "🍔": "sandwich", "🌭": "sandwich", "🌮": "sandwich", "🌯": "sandwich", "🥗": "salad", "🍩": "donut",
  "🍪": "cookie", "🍰": "cake-slice", "🎂": "cake-slice", "🍦": "ice-cream-cone", "🍭": "lollipop", "🍫": "cookie",
  "🍎": "apple", "🍊": "citrus", "🍋": "citrus", "🍌": "banana", "🍇": "grape", "🍓": "cherry", "☕": "coffee",
  "🍵": "coffee", "🍺": "beer", "🥂": "beer",
  "🎯": "target", "🎲": "dices", "🃏": "spade", "♠️": "spade", "♣️": "club", "♦️": "diamond", "♥️": "heart",
  "🎮": "gamepad", "🕹️": "gamepad", "🧩": "puzzle", "🏆": "trophy", "🥇": "medal", "🥈": "medal", "🥉": "medal",
  "🏅": "award", "🚀": "rocket", "✈️": "plane", "🚗": "car", "🚙": "car", "🏎️": "car", "🚌": "bus", "🚲": "bike",
  "⛵": "sailboat", "⚓": "anchor", "💎": "gem", "🛡️": "shield", "💣": "bomb", "🧨": "bomb", "🎨": "palette",
  "🎸": "guitar", "🎹": "piano", "🎵": "music", "🎶": "music", "🎧": "headphones", "📚": "book", "💼": "briefcase",
  "❤️": "heart", "🎁": "gift", "🎉": "party-popper", "🎊": "party-popper", "🧲": "magnet", "🗿": "mountain",
  "🎃": "ghost", "🧸": "paw-print", "🔮": "sparkles",
};

const ICONS_BY_ID = { ...UI_ICONS, ...Object.fromEntries(PLAYER_ICON_LIBRARY.map(([id, Icon]) => [id, Icon])) };

export function resolveIcon(value) {
  if (!value) return null;
  return ICONS_BY_ID[value] ?? ICONS_BY_ID[LEGACY_EMOJI[value]] ?? Smile;
}

export function toIconId(value) {
  if (!value || ICONS_BY_ID[value]) return value || "";
  return LEGACY_EMOJI[value] ?? "smile";
}
